 global:
   resolve_timeout: 5m
   smtp_smarthost: 'smtp.intel.com:25'
   smtp_from: 'alertmanager@openvino-monitoring.intel.com'
   smtp_require_tls: false

 route:
   group_by: ['job']
   group_wait: 30s
   group_interval: 5m
   repeat_interval: 12h
   receiver: 'null'

   routes:
   - match:
       severity: page
     continue: true
     repeat_interval: 15m
     receiver: 'telegram'
   - match:
       severity: page
     receiver: 'email'
   - match:
       severity: 'warning'
     receiver: 'email'

 receivers:
   - name: 'null'

   - name: 'email'
     email_configs:
     - to: 'vdp_monitoring@eclists.intel.com'
       send_resolved: true

   - name: 'telegram'
     webhook_configs:
     - send_resolved: true
       url: 'http://localhost:9116'
