---
version: '2.2'

networks:
  monitoring:

volumes:
  prometheus_data: {}
  alertmanager-bot_data: {}

services:
  blackbox-exporter:
    image: prom/blackbox-exporter:v0.16.0
    container_name: blackbox-exporter
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/blackbox.yml'
    network_mode: "host"

  nginx:
    image: nginx:1.17.6
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - alertmanager
      - prometheus
    network_mode: "host"

  prometheus:
    image: prom/prometheus:v2.16.0
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=366d'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    network_mode: "host"

  alertmanager:
    image: prom/alertmanager:v0.20.0
    container_name: alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    network_mode: "host"

  telegram-bot:
    image: metalmatze/alertmanager-bot:0.4.2
    container_name: telegram-bot
    environment:
      http_proxy: "http://proxy-dmz.intel.com:911"
      https_proxy: "http://proxy-dmz.intel.com:912"
      no_proxy: "localhost,127.0.0.1,intel.com,.intel.com"
      ALERTMANAGER_URL: http://localhost:9093
      BOLT_PATH: /data/bot.db
      STORE: bolt
      TELEGRAM_ADMIN: 
      TELEGRAM_TOKEN: 
      LISTEN_ADDR: 0.0.0.0:9116
    command:
      - '--log.level=debug'
    network_mode: "host"
    volumes:
      - alertmanager-bot_data:/data

